 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/messages", type: :request do
  include Devise::Test::IntegrationHelpers

  let(:user) { create(:user) }
  let(:room) { create(:room) }

  before do
    room

    sign_in user
  end

  let(:valid_attributes) {
    { content: 'Lorem Ipsum', room_id: room.id }
  }

  let(:invalid_attributes) {
    { content: '' }
  }

  context "when there are existing messages" do
    let(:message) { create(:message, user: user, room: room) }

    describe "GET /index" do
      it "renders a successful response" do
        get messages_url
        expect(response).to be_successful
      end
    end

    describe "GET /show" do
      it "renders a successful response" do
        get message_url(message)
        expect(response).to be_successful
      end
    end

    describe "GET /edit" do
      it "render a successful response" do
        get edit_message_url(message)
        expect(response).to be_successful
      end
    end

    describe "DELETE /destroy" do
      it "destroys the requested message" do
        delete message_url(message)

        expect(Message.count).to eq(0)
      end

      it "redirects to the messages list" do
        delete message_url(message)
        expect(response).to redirect_to(messages_url)
      end
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_message_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Message" do
        expect {
          post messages_url, params: { message: valid_attributes }
        }.to change(Message, :count).by(1)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Message" do
        expect {
          post messages_url, params: { message: invalid_attributes }
        }.to change(Message, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post messages_url, params: { message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end
end
